# Generated by Django 3.1.3 on 2020-12-13 10:09

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('create_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict', models.JSONField()),
                ('list', models.JSONField()),
            ],
            options={
                'verbose_name': 'Json表',
                'verbose_name_plural': 'Json表',
            },
            bases=(models.Model, utils.models.ModelSerializationMixin),
        ),
    ]
