# Generated by Django 3.1.3 on 2020-12-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_table', '0002_jsontable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jsontable',
            table='JsonTable',
        ),
    ]
